title: Jayaprakash Sundararaj
description: >-
  Personal Blog
domain: "jayaprakash.page"
url: "https://jayaprakash.page"
remote_theme: pages-themes/primer@v0.6.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
author: Jayaprakash Sundararaj
